name: todo-issues
run-name: ${{ github.actor }} - Action to create, update and close issues based on committed TODO comments
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5
